

module FromBNFC.AbsQFBF where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Formula
    = Equ Formula Formula
    | RImpl Formula Formula
    | LImpl Formula Formula
    | And Formula Formula
    | Or Formula Formula
    | XOr Formula Formula
    | Not Formula
    | Var Ident
  deriving (Eq, Ord, Show, Read)

