{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module FromBNFC.PrintQFBF where

-- pretty-printer generated by the BNF converter

import FromBNFC.AbsQFBF
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Formula where
  prt i e = case e of
    Equ formula1 formula2 -> prPrec i 1 (concatD [prt 2 formula1, doc (showString "<=>"), prt 2 formula2])
    RImpl formula1 formula2 -> prPrec i 2 (concatD [prt 3 formula1, doc (showString "==>"), prt 3 formula2])
    LImpl formula1 formula2 -> prPrec i 2 (concatD [prt 3 formula1, doc (showString "<=="), prt 3 formula2])
    And formula1 formula2 -> prPrec i 3 (concatD [prt 4 formula1, doc (showString "and"), prt 4 formula2])
    Or formula1 formula2 -> prPrec i 4 (concatD [prt 5 formula1, doc (showString "or"), prt 5 formula2])
    XOr formula1 formula2 -> prPrec i 4 (concatD [prt 5 formula1, doc (showString "xor"), prt 5 formula2])
    Not formula -> prPrec i 5 (concatD [doc (showString "not"), prt 6 formula])
    Var id -> prPrec i 6 (concatD [prt 0 id])


